version: '3'

services:
  web:
    build: .
    ports:
      - "8099:8099"
    volumes:
      - .:/app
      - "./static:/app/static"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

volumes:
  db-data:
